import sys
import fileinput
import numpy

# This script takes as input Depth of coverage files generated by GATK DepthOfCoverage and calculates the sum of depths over 1kb windows
# for each ReadGroup ID (depth column). The maximum number of individuals (more specifically RG iDs) 170)
# Carl-Johan Rubin, Uppsala University, 2016
def CalcCov(infile):
	counter=0
	Cov=0
	counter2=0
	array1=numpy.zeros([170],int)
	cov1=0
	pos=0
	lastpos=0
	for line in fileinput.input(infile):
		counter2=counter2+1
		counter=counter+1
		line=line.replace('\n','')
		line=line.replace(':','\t')
		cols=line.split('\t')
		lenCols=len(cols)
		if counter2>1:
			pos=int(cols[1])
		elif counter2==1:
			pos=1
			counter=0
		if counter==1:
			lastpos=pos
		if counter >1:
			pos=int(cols[1])
			for iter in range(lenCols-4):
				array1[iter]=int(cols[4+iter])+array1[iter]
			if counter==1000:
				print str(cols[0]) + '\t' + str(lastpos)+ '\t' + str(pos)+ '\t',		
				for iter2 in range(lenCols-4):
					cov1=array1[iter2]
					print str(cov1) + '\t',
				print '\n',
				counter=0
				array1=numpy.zeros([170],int)

			
		

				

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print 'Wrong number of arguments!\n'
        sys.exit(2)
    CalcCov(sys.argv[1],)
